[project]
name = "doge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "curl-cffi>=0.10.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
