name: DOGE update nightly cronjob

on:
  push:
    branches:
      - main
  schedule:
    - cron: '16 12 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Write access is needed to push changes back to the repository
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5.4.1
        with:
          version: "latest"

      - name: Running backup script
        run: |
          uv run python main.py data/raw/

      - name: Commit and push changes
        if: github.ref == 'refs/heads/main'
        run: |
          git status
          git config --local user.email "noreply@github.com"
          git config --local user.name "github-actions[bot]"
          git add data/raw/
          if ! git diff-index --quiet HEAD; then
            git commit -m 'Nightly update of raw DOGE changes - $(date +'%Y-%m-%d')'
            git push -u origin main
          fi
