name: DOGE update nightly cronjob

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: '16 12 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Running backup script
        run: |
          uv run python main.py data/raw/

      - name: Set date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Commit DOGE changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Github Action Bot
          author_email: noreply@github.com
          message: 'Nightly update of raw DOGE changes - ${{ steps.date.outputs.date }}'
          add: 'data/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
